### PR TITLE
phase 3

### PR DESCRIPTION
**Pull request by jeanniedavis**
This is phase 3 
It handles the game logic
Note: there is a bug still -- will fix it tomorrow as it is late and I am tired lol 
Note: **DO NOT MERGE**

### CODE REVIEW

**Comment by apainintheneck** [comment]
I have some questions.

1. On lines 69-84, what is the purpose of the timer?
2. Does the human always go first? If not, then the computer's card should show before the human plays.
3. Shouldn't we add something to count the scores of each player?
4. Shouldn't we add a screen at the end of the game showing the score and the winner?

I'm going to create a new branch and try to add scores and an ending screen.

**Comment by apainintheneck** [comment]
Also, what does userMove measure?

**Comment by apainintheneck** [comment]
Sorry, accidentally closed the PR.

**Comment by jeanniedavis** [comment]
@apainintheneck 
1. Human goes first only the first hand
2. The purpose of the timer is because you want a small delay between the cpu playing the card/the end of the previous round. 
3. Yes I need to add this still will add this and an end screen later -- i first need to fix the race condition in the game
4. userMove measures who won previously (will add more comments)

**Comment by jeanniedavis** [comment]
@apainintheneck no need for you to make the branch for that, I can do it later on tonight. Won't be too much work. 
The main issue that I have right now is that sometimes the value of the CPU's card is not correct. An example I ran into was the CPU's drawn card was a 2 but had the value of a Q. I can fix it fairly quickly I just don't have time at the very moment

**Comment by jeanniedavis** [comment]
But yes, more comments are needed -- i was just too tired at 3am to write all my comments sorry

**Comment by apainintheneck** [comment]
Also, when a card has yet to be played by either the human or computer, I think you should just make that label invisible. Something like Label.setVisible(false).

**Comment by jeanniedavis** [comment]
oh also the delay is 2 seconds, so if you're trying it out just wait 2 seconds between each card

**Comment by apainintheneck** [comment]
Wouldn't it be easier to use Thread.sleep(x) than creating a timer. You have to wrap it in a try/catch but I think it's better than having to create a new timer object each time. This is what I did in the testCardTable.java file.

**Comment by jeanniedavis** [comment]
so Thread.Sleep(x) does the entire thread which isn't what i need it to do.
I already tried using Thread.Sleep and it didn't full work the way that I wanted it to

**Comment by apainintheneck** [comment]
That's weird. I wouldn't have expected that.

**Comment by apainintheneck** [comment]
After looking more at the code, I have a few more thoughts.

It seems like the cards are played and chosen for both players in the actionListener for each card button. This means that it is impossible for the computer's card to be chosen before the human's card because it happens afterwards. There are two possible solutions to this, as I see it.

1. Make the human play first every time. I don't think there is anything in the spec that says the players have to alternate turns(though he does mention that it is something that you can try). This would be the simplest way to change the program.

2. Make winner play first. This requires the computer to be able to choose and play a card outside of the actionListener. It also requires some way to stop listening to button presses when it is not the human's turn or a button has already been pressed. This is way harder and probably unnecessary.

**Pull request merged**
